Repository keylime/keylime, pull requests merged in 2022-12, with the labels that each got.

#1230 cmd: removal of keylime_migrations_apply
  keylime/cmd/registrar.py
  keylime/cmd/verifier.py
  keylime/common/migrations.py
  setup.cfg
Labels: breaking-change, cleanup

#1229 common: remove metrics
  keylime/common/metrics.py
Labels: cleanup

#1236 codestyle: Add missing annotations to crypto.py and add to mypy
  keylime/crypto.py
  mypy.ini
Labels: cleanup

#1235 codestyle: Type-annotate secure_mount.py
  keylime/secure_mount.py
  mypy.ini
Labels: cleanup

#1240 logging: remove option to log into separate file
  keylime.conf
  keylime/keylime_logging.py
  scripts/templates/2.0/registrar.j2
  scripts/templates/2.0/verifier.j2
Labels: breaking-change, cleanup

#1232 codestyle: Type-annotate web_util.py
  keylime/cloud_verifier_tornado.py
  keylime/registrar_common.py
  keylime/web_util.py
  mypy.ini
  test/test_web_util.py
Labels: cleanup

#1234 codestyle: add type hints to elchecking module
  keylime/elchecking/__main__.py
  keylime/elchecking/example.py
  keylime/elchecking/policies.py
  keylime/elchecking/tests.py
  mypy.ini
Labels: cleanup

#1233 codestyle: Fix some issues with type annotiations in the verifier
  keylime/cloud_verifier_tornado.py
Labels: cleanup

#1248 api_version: Catch InvalidVersion for packaging v22.0
  keylime/api_version.py
Labels: bugfix

#1250 codestyle: Add missing type annotions to files in common & add to mypy
  keylime/common/algorithms.py
  keylime/common/exception.py
  keylime/common/migrations.py
  keylime/common/retry.py
  keylime/common/states.py
  keylime/common/validators.py
  mypy.ini
  test/test_retry_algo.py
Labels: cleanup

#1249 Remove redundant parameter from enforce_pcrs()
  keylime/cli/policies.py
Labels: cleanup

#1253 tpm_abstract: move import of measured_boot into check_pcrs(..)
  keylime/tpm/tpm_abstract.py
Labels: bugfix

#1243 verifier: a (very simple) cache implementation for IMA policies (solves #1167)
  keylime/cloud_verifier_tornado.py
Labels: bugfix, feature

#1255 elchecking: add support for measured boot when SecureBoot is disabled
  keylime/elchecking/example.py
  scripts/create_mb_refstate
Labels: feature

#1257 Fix the ima_sign_verification_keys initial datatype
  keylime/cli/policies.py
  keylime/ima/file_signatures.py
  keylime/tenant.py
Labels: bugfix, cleanup
