Repository keylime/keylime, pull requests merged in 2023-05, with the labels that each got.

#1358 web_util: handle tls_dir default with cacerts correctly
  keylime/web_util.py
Labels: bugfix

#1387 docs: remove Vagrant setup
  docs/installation.rst
Labels: cleanup, docs

#1383 Registrar: Consolidate repetitive checking of input parameters
  keylime/registrar_common.py
Labels: cleanup

#1384 cloud_verifier: AgentsHandler: Consolidate checking of input parameters
  keylime/cloud_verifier_tornado.py
Labels: cleanup

#1389 IMA: cleanups and simplifications
  keylime/ima/ima.py
Labels: cleanup
