Repository keylime/keylime, pull requests merged in 2023-01, with the labels that each got.

#1277 tenant: fix the exit code for `bulkinfo` operation
  keylime/tenant.py
Labels: bugfix

#1271 tenant: reliable and consistent add/delete operations (fixes #1158)
  keylime/tenant.py
Labels: bugfix, cleanup

#1276 pylint: ingore zmq Context abstract-class-instantiated warnings
  keylime/revocation_notifier.py
Labels: cleanup

#1258 durable attestation: a simple "attestation replay" CLI utility
  keylime/cmd/attest.py
  keylime/da/attest.py
  keylime/da/examples/file.py
  keylime/da/examples/redis.py
  keylime/da/examples/sqldb.py
  keylime/da/record.py
  mypy.ini
  setup.cfg
Labels: enhancement, feature

#1279 Update and extend experimental create_policy tool
  scripts/create_policy
Labels: cleanup, feature

#1280 pylintc: Remove outdated modules from list of ignore modules
  pylintrc
Labels: cleanup
