Repository keylime/keylime, pull requests merged in 2023-03, with the labels that each got.

#1322 ima: do not validate against the allowlist if signature was already validated
  keylime/ima/ima.py
  test/test_ima_verification.py
Labels: breaking-change

#1317 create_policy: read the hashes from filelists-ext
  scripts/create_policy
Labels: feature

#1289 remove Python agent
  .packit.yaml
  ima_stub_service/README.md
  ima_stub_service/ima_emulator.service
  ima_stub_service/installer.sh
  ima_stub_service/tpm_emulator.service
  installer.sh
  keylime/agentstates.py
  keylime/ca_util.py
  keylime/cmd/agent.py
  keylime/cmd/ima_emulator_adapter.py
  keylime/common/algorithms.py
  keylime/config.py
  keylime/crypto.py
  keylime/keylime_agent.py
  keylime/measured_boot.py
  keylime/registrar_client.py
  keylime/revocation_actions/__init__.py
  keylime/revocation_actions/print_metadata.py
  keylime/revocation_actions/update_crl.py
  keylime/revocation_notifier.py
  keylime/secure_mount.py
  keylime/tpm/tpm_abstract.py
  keylime/tpm/tpm_main.py
  keylime/tpm_ek_ca.py
  keylime/user_utils.py
  keylime/user_utils_test.py
  keylime/web_util.py
  mypy.ini
  packit-ci.fmf
  pyproject.toml
  services/installer.sh
  services/keylime_agent.service
  services/keylime_agent.service.template
  services/var-lib-keylime-secure.mount
  setup.cfg
  test/oldtest.py
  test/run_tests.sh
  test/test_ca_util.py
  test/test_cert_utils.py
  test/test_config.py
  test/test_secure_mount.py
  test/test_tpm.py
Labels: breaking-change, cleanup

#1331 Add JSON schema for runtime policy and validate user-provided runtime policies against it
  keylime/cloud_verifier_tornado.py
  keylime/ima/ima.py
  keylime/ima/ima_test.py
  keylime/tenant.py
  requirements.txt
  test/run_tests.sh
Labels: dependencies

#1314 Implement DSSE signing/verification for Keylime runtime policies
  keylime/cli/options.py
  keylime/cli/policies.py
  keylime/cloud_verifier_tornado.py
  keylime/cmd/sign_runtime_policy.py
  keylime/dsse/__init__.py
  keylime/dsse/dsse.py
  keylime/dsse/ecdsa.py
  keylime/dsse/x509.py
  keylime/ima/ima.py
  keylime/signing.py
  keylime/tenant.py
  setup.cfg
  test/data/ecdsa-sig-key.pub
  test/data/runtime-policy-bad.sig
  test/data/runtime-policy-pubkey.pub
  test/data/runtime-policy-test-signed-bad.json
  test/data/runtime-policy-test-signed.json
  test/data/runtime-policy-test.sig
  test/test_ima_verification.py
Labels: enhancement, breaking-change, feature

#1318 Install create_policy as keylime_create_policy, annotate sources, and extend it
  docs/user_guide/runtime_ima.rst
  keylime/cmd/create_policy.py
  keylime/signing.py
  keylime/types.py
  scripts/check_codestyle.sh
  setup.cfg
Labels: cleanup, feature
