Repository keylime/keylime, pull requests merged in 2023-02, with the labels that each got.

#1303 Fix stray references to "IMA policies" in conversion script
  keylime/cmd/convert_runtime_policy.py
Labels: breaking-change, cleanup

#1272 fix: type issues in verifier's code
  keylime/cloud_verifier_tornado.py
  pyproject.toml
Labels: cleanup

#1312 db: switch to pessimistic disconnect handling
  keylime/db/keylime_db.py
Labels: bug

#1313 Add timestamp of last successful attestation to verifier API (enhancement #74) and address some missing documentation
  docs/rest_apis.rst
  keylime/cloud_verifier_common.py
  keylime/cloud_verifier_tornado.py
  keylime/db/verifier_db.py
  keylime/migrations/versions/f838d3cdeead_add_last_successful_attestation.py
Labels: enhancement, feature
